sudo: false
dist: trusty
language: rust

env:
  global:
    - secure: IyWCw7Tcp17uG9JCVazTyCzgtBAtFQk2jPsf3zcpNqqWKJasz+CSHfuKUbqa8i20dlAtFgL/ZvgKN9cRgqmbhDDZ1lcvX8mqJtkdy5H5sQQd8VamqnI3f5Em+Qk9BquXlBx/zm0k44pNfyt2JkiaxBdoOXcAD+wTUMhBn5ozQXNBUkdoOiDBODizR/4ZuzBVZGg7zrZRNV8nvZVOglO6nQxwFNSHGjXjPT6b3TmFKhrCtQH/ZIt8Ip42nm3wc6XNLSWj5/0h/erm9vz2IZyDopysP7vhdXzLOlCXCVVgguXXRqHWNevvn5FHiL0FQnhoL8aRK40sAMTMaHhvieuRxXmEtsgV7IK5U4ST0ZOTlCLhBr5je7gcuEvxDeZ2fQTd8fFtJpXl9zGPsR/mGR11xtCXh2AFmbOwnP4iUS3u+0bQ5b+FPWtKi178aLFqdAYDeze49HdnW/4G88EU+LylwpTzR/HYMMdVinYU48pW6XPwX9WmXbSjXZ2z8wWXBjnlc8ANOHSgE7+Fhzbn4HsJCBrneDE9qbrKGykfuLzO9OGeVh1xU4qBQxXRJ6jaJ9l4MHCe5dJryfZSEnnghEjLOObCu63a+tuNsDxbFGSjSST3hpX6M1niQlLmLa8/KMjqKn88oCviQ7T+cMoxP8ZBP/acTh2ZqeQR0lM+uj6Q6Io=
    - secure: pzdGlrwj3z9mu2PaOMLbu/Bg7eSLd0ActgOm9i3fDVC+pfkaakd2AeDLREPhlIrIrFo1Rrz5fpa96pReCC51pYA+sCQqQfOVCSYPgPxKq9lUUo9F4M4LxtVfy2ki8yIcBPTZdxVeuyybb3RD3ATJ9mLAPkebA3WBEHO7yVwOaFwP9l/qtfcj7LwOCAw2wMZqAQEsrcnvWcIPm61GNjZ7RBWZg9fGnycM+dhofjKC2Z3j9VNbfREdrMdzux7wG2BcNaifqMzalM59CCxC9+eT2QvTwoCrPpDT3SZie01pKE/xrn02FS2PAavmSWUry2YvWk8EVkA4tMu8tcLtWZR+ry8BWL+yDwrfdjr0B9R6uTdSyjT0dYtUjD0x7gZpE6fySGwOkYZbLW0GjO4xpuA/D5TBv9ZjzdumxTD8o8NVbVztumAb8eWB2t0qL1IZ7L/YAAk3B9UBF2+R++fh6a/bmO9Zy319LefJi8cKsDl9TuOt/2s3SbUd0FU5hQUf3m+pv3ME2McEeXl5xU6AwHb+RHQ/WOFNrSsDf2MWWwry+i89eVX82buyNhbWxZxpVNWhT9X5quELcu97mje5/TcUbAIl+8j7mYWAFenUTnt4CgLBxi3AQLl9SFjqOYBvubbUjg/f9pb+zN21Itg+fhWjV8jZc09ljcyD+1Lgc1mUKTM=
    - secure: JzDhSZOuuINr9PuK33AD0v8U7vQoonjOrzwBf217RugC7mVrraNIGfe0bIzUes8h6yCz8YASVPvN4kjiXcmJjFHNymMMBI1ZzpYwj+Vb8QXis/DMRHENY8Xh3KgNwtkAobKZKqeYZRVd2oDsFKeX2O9FTmFYsNq+mWtJrDss4yuKQIRM8EYVEEPI+mUlKYAOB677APaaarnnlgnVIJmcnFZrKIwrkBWg9HXW+/G7FPVbIl2OFVL1MiSlz7ZC2VOmaV+V7MJpU3YeF9usdeXhhkJd+hivn3q4x4NUhSHETbYjPehel7Rewc18dV0r4L2qJfKsxpR/v80ZaGkYaAjl0sO6I+8mjuswo+rmsAp3WA+HxSvgr2Qb57RuFJgO2UC/de6mVNHODREuuwkfcypKGgoQXFperpjTO7/7pwlUKbmyz2I6Y1C82KlMCpKRnG+iMSkproZRsIEKb2AfDB43v3vF4iy98yXOCuCsCmVAhF51dxLX2m3NtIM4uO37C1cVlrwChNXP5772I6b7uW+9JRAOkf0ON/snP6sDPoQHYs2cpFyi+9AocZTCNePY/dlICmVQY6aK4EIq1bVFNBjJMl3y8pON/iubrjIEW4UpGLPtukrVu9HeoTxRtSCW3ckmrQN5xnmXEkQP1uJPqnvFTafPlHaRif0pF3XSC7XVa1o=

git:
  lfs_skip_smudge: true

cache:
  yarn: true
  pip: true
  cargo: true
  directories:
    - node_modules

before_install:
  - nvm install 8.9.4
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - pip install --user awscli
  - export PATH=$HOME/.yarn/bin:$PATH
  - git lfs install

install:
  - yarn
  - cd tools && cargo build --verbose --release && cd ..

before_script:
  - git lfs pull

script:
  - travis_wait yarn build

deploy:
  provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master
